### ISSUE TITLE
The package is not published to NPM

### ISSUE THREAD

**Issue by greyblake** [winoteam/rescript-big#12]
Hi, thanks for the bindings!
It does not look like the package `@wino/rescript-big` exists on NPM server, or I am missing something?

**Comment by LeoLeBras** [comment]
Hello 👋

`@wino/rescript-big` is a private package.
I just released on npm `rescript-big@v4` !

Greetings from Paris 🇫🇷

**Comment by greyblake** [comment]
@LeoLeBras Merci beaucoup!
